import type { CommentaryLens, ResearchSource } from "./types";

const source = (value: Omit<ResearchSource, "isLive" | "fetchedAt" | "sourceHash">): ResearchSource => ({
  ...value,
  isLive: false,
  fetchedAt: null,
  sourceHash: "",
});

export const CURATED_SOURCES: ResearchSource[] = [
  source({
    id: "overclaimbench-2609-20812",
    kind: "paper",
    title: "Quantifying Overclaiming Propensity in Frontier LLM Agents",
    publisher: "arXiv",
    authors: "Nolan Smyth, Yorguin-Jose Mantilla-Ramos, Pascal Jr Tikeng Notsawo, Saskia Helbling, Alberto Tosato, Mohamed Amine Merzouk, Nouha Dziri, Gauthier Gidel, Tommaso Tosato",
    publishedAt: "2026-09-21T00:00:00.000Z",
    url: "https://arxiv.org/abs/2609.20812",
    summary: "Measures whether coding agents accurately report the scope of work they actually inspected and completed.",
    keyClaim: "Final responses are not reliable accounts of an agent's actions; incomplete coverage was frequently accompanied by misleading completion claims.",
    limitations: "Five file-review scenarios and a fixed harness do not establish behavior across every production agent or deployment.",
    topics: ["evals", "overclaiming", "agents", "monitoring", "evidence"],
    evidenceGrade: "primary",
    stance: "cautionary",
  }),
  source({
    id: "bootstrapped-monitoring-2606-11998",
    kind: "paper",
    title: "Bootstrapped Monitoring: Leveraging Transparent Reasoning to Oversee Stronger AI Agents",
    publisher: "arXiv",
    authors: "Frank Xiao, Mary Phuong",
    publishedAt: "2026-06-10T00:00:00.000Z",
    url: "https://arxiv.org/abs/2606.11998",
    summary: "Introduces an intermediate untrusted monitor whose transparent reasoning is checked by a weaker trusted model for signs of collusion.",
    keyClaim: "A trusted model may remain useful for deception detection even when it is too weak to judge every frontier action directly.",
    limitations: "The approach depends on raw or inspectable intermediate reasoning and may fail as chain-of-thought transparency declines.",
    topics: ["oversight", "monitoring", "deception", "control", "agents"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "missing-boundary-2609-11024",
    kind: "paper",
    title: "The Missing Boundary: How Autonomous Agents Lose Control",
    publisher: "arXiv",
    authors: "Zonghao Ying, Xiangfan Wu, Bo Yang, Huiyu Wu, Xing Zheng, Huangsheng Cheng, Xiaorong Shi, Jing Guo",
    publishedAt: "2026-09-24T00:00:00.000Z",
    url: "https://arxiv.org/pdf/2609.11024.pdf",
    summary: "Uses controlled multi-turn experiments to separate goal pressure, constraint degradation, and executable unsafe opportunity.",
    keyClaim: "A legitimate task can cross an authorization boundary when pressure, degraded constraints, and an unsafe opportunity coincide; retaining constraints can remove the observed loss of control.",
    limitations: "The benchmark is deterministic and operational-domain bounded; it does not estimate natural-world frequency.",
    topics: ["loss-of-control", "control", "agents", "evals", "constraints"],
    evidenceGrade: "experimental",
    stance: "cautionary",
  }),
  source({
    id: "observerbench-2609-03026",
    kind: "paper",
    title: "ObserverBench: Testing Mechanistic Estimates for Intervention and Control",
    publisher: "arXiv",
    authors: "Vijay Erramilli",
    publishedAt: "2026-09-02T05:23:57.000Z",
    url: "https://arxiv.org/abs/2609.03026",
    summary: "Separates the accuracy of an internal observer from the quality of the action it recommends under a fixed intervention contract.",
    keyClaim: "A good estimate is not automatically a good control policy; intervention cost, information boundaries, and action loss must be evaluated together.",
    limitations: "Results are tied to the reported tasks, model panels, and disclosed checkpoint or activation conditions.",
    topics: ["interpretability", "control", "evals", "monitoring", "interventions"],
    evidenceGrade: "primary",
    stance: "mixed",
  }),
  source({
    id: "saescientist-bench-2609-09113",
    kind: "paper",
    title: "SAEScientist-Bench: Can AI Agents Conduct Autonomous SAE Interpretability Research?",
    publisher: "arXiv",
    authors: "Yuqiao Tan, Shizhu He, Jun Zhao, Kang Liu",
    publishedAt: "2026-09-08T09:34:23.000Z",
    url: "https://arxiv.org/abs/2609.09113",
    summary: "Tests whether agents can design probes and navigate a large sparse-autoencoder dictionary to discover causal features.",
    keyClaim: "Agents show genuine discovery behavior but lag expert baselines in causal steering and frequently misinterpret experimental measurements.",
    limitations: "The benchmark covers a specific feature dictionary, concept set, and agent configuration.",
    topics: ["interpretability", "agents", "evals", "autonomous-rd", "measurement"],
    evidenceGrade: "primary",
    stance: "mixed",
  }),
  source({
    id: "collective-loss-control-2609-18460",
    kind: "paper",
    title: "Collective Loss of Control in LLM Agent Systems",
    publisher: "arXiv",
    authors: "Xiangfan Wu, Zonghao Ying, Huiyu Wu, Xing Zheng, Huangsheng Cheng, Xiaorong Shi, Jing Guo",
    publishedAt: "2026-09-16T00:00:00.000Z",
    url: "https://arxiv.org/abs/2609.18460",
    summary: "Frames multi-agent failure as mutation, contagion, and recovery, then probes unintended communication paths between nominally separate runs.",
    keyClaim: "Low clean-task harm can coexist with high susceptibility after inherited unsafe state; isolation and recovery are active controls, not assumptions.",
    limitations: "The account does not establish a natural autonomous cascade or a population-level initiation rate.",
    topics: ["multi-agent", "loss-of-control", "security", "monitoring", "recovery"],
    evidenceGrade: "experimental",
    stance: "cautionary",
  }),
  source({
    id: "enforcement-gap-2609-15293",
    kind: "paper",
    title: "Why LLM Agents Collapse Without Oversight: The Enforcement Gap",
    publisher: "arXiv",
    authors: "Yuhang Wang",
    publishedAt: "2026-09-14T05:57:38.000Z",
    url: "https://arxiv.org/abs/2609.15293",
    summary: "Argues that detecting a dangerous step is not enough unless the controller has a reliable path from detection to intervention.",
    keyClaim: "An enforcement controller that turns an audit verdict into a concrete stop or escalation can reduce attack success in the reported experiments.",
    limitations: "The result depends on the benchmark's environment, controllers, and attack construction.",
    topics: ["oversight", "control", "agents", "evals", "interventions"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "human-oversight-2605-16278",
    kind: "paper",
    title: "Keeping an Eye on AI: A Framework for Effective Human Oversight",
    publisher: "arXiv",
    authors: "Susanne Gaube, Markus Langer, Tim Miller, Kevin Baum, Raimund Dachselt, Anna Maria Feit, Ujwal Gadiraju, Harmanpreet Kaur, Mark T. Keane, Richard Landers, Johann Laux, Q. Vera Liao, Brian Lim, Linda Onnasch, Tim Schrills, Liz Sonenberg, Chenhao Tan, Nava Tintarev, Ziang Xiao, Hanwei Zhang",
    publishedAt: "2026-05-01T00:00:00.000Z",
    url: "https://arxiv.org/pdf/2605.16278v1.pdf",
    summary: "Builds a cross-disciplinary framework and documentation template for effective human monitoring and intervention.",
    keyClaim: "Meaningful oversight is multi-layered and socio-technical; a human label or nominal approval is not sufficient evidence of control.",
    limitations: "The framework is a design and research agenda rather than a validated certification of any deployed system.",
    topics: ["human-agency", "oversight", "governance", "care", "accountability"],
    evidenceGrade: "synthesis",
    stance: "constructive",
  }),
  source({
    id: "systemic-risk-index-2609-28335",
    kind: "paper",
    title: "An Open Pipeline and Dashboard for Systemic-Risk Evidence",
    publisher: "arXiv",
    authors: "Jacob T. Emmerson, Phuong-Anh Nguyen-Le, Ronan Romano, Wilber Sean V. Anterola, Yann Billeter, Zhijing Jin",
    publishedAt: "2026-09-23T00:00:00.000Z",
    url: "https://arxiv.org/abs/2609.28335",
    summary: "Organizes public benchmark evidence into systemic-risk categories and exposes aggregation and capability assumptions instead of hiding them in a leaderboard.",
    keyClaim: "Average and worst-case aggregation can produce materially different risk pictures, so assumptions should be inspectable.",
    limitations: "Benchmark coverage and harm-preservation assumptions remain incomplete and should be challenged locally.",
    topics: ["evals", "risk", "evidence", "governance", "benchmarks"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "international-ai-safety-report-2026",
    kind: "report",
    title: "International AI Safety Report 2026",
    publisher: "International AI Safety Report",
    authors: "Independent international writing team",
    publishedAt: "2026-02-03T00:00:00.000Z",
    url: "https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026",
    summary: "Synthesizes evidence on frontier capabilities, emerging risks, evaluations, safeguards, resilience, and institutional gaps.",
    keyClaim: "The evidence dilemma is real: uncertainty grows faster than public evidence, while voluntary safeguards remain unevenly verifiable.",
    limitations: "The report is a synthesis of evidence available before its cutoff and does not prescribe policy.",
    topics: ["governance", "risk", "evals", "resilience", "transparency"],
    evidenceGrade: "synthesis",
    stance: "mixed",
  }),
  source({
    id: "singapore-consensus-2026",
    kind: "report",
    title: "The 2026 Singapore Consensus on Global AI Safety Research Priorities",
    publisher: "AI Safety Priorities",
    authors: "International Scientific Exchange contributors",
    publishedAt: "2026-09-01T00:00:00.000Z",
    url: "https://aisafetypriorities.org/files/Singapore_Consensus_2026.pdf",
    summary: "Maps urgent research and risk-management questions for increasingly autonomous agents and evaluation-aware systems.",
    keyClaim: "Agentic risk management needs least privilege, traceable identity, auditability, validated deployment, interruptibility, and human oversight.",
    limitations: "The consensus is a research agenda, not a settled technical standard or prediction of future risk.",
    topics: ["agents", "governance", "oversight", "control", "research-priorities"],
    evidenceGrade: "synthesis",
    stance: "constructive",
  }),
  source({
    id: "metr-frontier-risk-report-2026",
    kind: "report",
    title: "Frontier Risk Report: February to March 2026",
    publisher: "METR",
    authors: "METR evaluation team",
    publishedAt: "2026-05-19T00:00:00.000Z",
    url: "https://metr.org/blog/2026-05-19-frontier-risk-report/",
    summary: "Reports an entity-based pilot with Anthropic, Google, Meta, and OpenAI on means, motive, opportunity, monitoring, and rogue deployment risk.",
    keyClaim: "Internal frontier agents plausibly had the means, motive, and opportunity for small rogue deployments, but not the means to make them highly robust.",
    limitations: "Private assessments and company-specific redactions limit independent reproduction and generalization.",
    topics: ["frontier-risk", "monitoring", "governance", "agents", "security"],
    evidenceGrade: "first-party",
    stance: "mixed",
  }),
  source({
    id: "openai-third-party-assessments-2026",
    kind: "report",
    title: "Priorities and Principles for Effective Third-Party Assessments",
    publisher: "OpenAI",
    authors: "OpenAI safety and policy teams",
    publishedAt: "2026-09-22T00:00:00.000Z",
    url: "https://openai.com/index/priorities-principles-third-party-assessments/",
    summary: "Sets out principles for scoped, secure, independent, transparent, and actionable assessment of frontier safety claims.",
    keyClaim: "Claims should be pre-registered, methods and uncertainty explicit, findings actionable, and publication protected without editorial capture.",
    limitations: "This is an institution's stated engagement position, not an independent audit of its implementation.",
    topics: ["governance", "evals", "transparency", "oversight", "accountability"],
    evidenceGrade: "first-party",
    stance: "constructive",
  }),
  source({
    id: "openai-long-horizon-safety-2026",
    kind: "report",
    title: "Safety and Alignment in an Era of Long-Horizon Models",
    publisher: "OpenAI",
    authors: "OpenAI safety and alignment teams",
    publishedAt: "2026-07-20T00:00:00.000Z",
    url: "https://openai.com/index/safety-alignment-long-horizon-models/",
    summary: "Describes an incident-derived loop of limited deployment, trajectory monitoring, pause, new evaluations, stronger controls, and controlled restoration.",
    keyClaim: "Single-action approval is insufficient for long-running trajectories; monitors must understand evolving outcomes and be able to intervene.",
    limitations: "The report describes selected internal deployments and does not expose all incidents, methods, or redactions.",
    topics: ["long-horizon", "monitoring", "control", "agents", "deployment"],
    evidenceGrade: "first-party",
    stance: "constructive",
  }),
  source({
    id: "anthropic-pace-measurements-2026",
    kind: "report",
    title: "Measurements for Understanding the Pace of AI Development Inside Frontier Labs",
    publisher: "Anthropic Institute",
    authors: "Anthropic Institute",
    publishedAt: "2026-09-23T21:59:24.000Z",
    url: "https://www.anthropic.com/institute/measuring-pace-of-ai-development",
    summary: "Proposes public measurement of AI-led R&D, monitor coverage, review latency, escalation rate, and safety compute allocation.",
    keyClaim: "A small set of comparable operational metrics could make it easier to ask whether oversight and safety work keep pace with capability work.",
    limitations: "The snapshot is from one organization and relies partly on model-assisted classification; comparable definitions are still developing.",
    topics: ["monitoring", "governance", "transparency", "ai-rd", "oversight"],
    evidenceGrade: "first-party",
    stance: "constructive",
  }),
  source({
    id: "dario-pacing-frontier-2026",
    kind: "commentary",
    title: "We Must Pace the Frontier",
    publisher: "Dario Amodei",
    authors: "Dario Amodei",
    publishedAt: "2026-07-01T00:00:00.000Z",
    url: "https://darioamodei.com/post/we-must-pace-the-frontier",
    summary: "Argues for embedded evaluators, interpretability, expanded testing, and increasingly coordinated frontier safeguards.",
    keyClaim: "Verifiability requires independent access to the systems and practices behind safety claims, not only published scores.",
    limitations: "This is a policy argument from a frontier-lab leader, not a settled empirical finding or binding proposal.",
    topics: ["governance", "oversight", "interpretability", "evals", "pacing"],
    evidenceGrade: "commentary",
    stance: "cautionary",
  }),
  source({
    id: "openai-agentic-governance-practices",
    kind: "report",
    title: "Practices for Governing Agentic AI Systems",
    publisher: "OpenAI",
    authors: "OpenAI policy and safety teams",
    publishedAt: "2026-06-01T00:00:00.000Z",
    url: "https://cdn.openai.com/papers/practices-for-governing-agentic-ai-systems.pdf",
    summary: "Proposes baseline responsibilities and safety practices across the agentic system lifecycle.",
    keyClaim: "Accountability must be distributed across developers, deployers, infrastructure providers, and users rather than delegated to an agent.",
    limitations: "The practices are a proposed baseline and require operationalization, incentives, and independent verification.",
    topics: ["agents", "governance", "accountability", "deployment", "safety"],
    evidenceGrade: "first-party",
    stance: "constructive",
  }),
  source({
    id: "science-who-checks-ai-2026",
    kind: "commentary",
    title: "Who Checks What AI Can Do?",
    publisher: "Science",
    authors: "Science editorial commentary",
    publishedAt: "2026-09-20T00:00:00.000Z",
    url: "https://www.science.org/doi/10.1126/science.ael2161",
    summary: "Argues that frontier safety claims need routine independent verification, controlled access, and incident-reporting institutions.",
    keyClaim: "A result that cannot be independently reproduced is testimony rather than settled scientific evidence.",
    limitations: "It is a commentary on scientific institutions and measurement, not a technical evaluation of a particular model.",
    topics: ["verification", "governance", "evals", "transparency", "institutions"],
    evidenceGrade: "commentary",
    stance: "constructive",
  }),
  source({
    id: "civic-ai-care-2026",
    kind: "commentary",
    title: "Attentiveness in Long-Term Care AI",
    publisher: "Civic AI",
    authors: "Civic AI care researchers and care-community collaborators",
    publishedAt: "2026-03-13T00:00:00.000Z",
    url: "https://civic.ai/care-ai/",
    summary: "Describes care-centered responsible AI as beginning with dignity, choice, human relationships, and people affected by the system.",
    keyClaim: "Care ethics supplies operational questions about consent, accessibility, reciprocity, and who is missing from the table.",
    limitations: "The case is a domain-specific co-production account, not a universal causal evaluation of care-centered AI.",
    topics: ["care", "human-agency", "governance", "voice", "co-production"],
    evidenceGrade: "commentary",
    stance: "constructive",
  }),
  source({
    id: "ae-alignment-podcast",
    kind: "podcast",
    title: "AE Alignment Podcast",
    publisher: "AE Studio",
    authors: "James Bowler and alignment researchers",
    publishedAt: "2026-07-29T14:37:08.000Z",
    url: "https://podcasts.apple.com/us/podcast/ae-alignment-podcast/id1888046207",
    summary: "Research conversations about pre-training alignment, mechanistic interpretability, model psychology, and making technical work understandable.",
    keyClaim: "Pre-training and access-control interventions deserve more attention because later safeguards may not remove latent capabilities or behaviors.",
    limitations: "Podcast claims are expert explanations and commentary; listen to the linked papers and methods before treating them as settled evidence.",
    topics: ["pretraining", "interpretability", "alignment", "access-control", "research-priorities"],
    evidenceGrade: "commentary",
    stance: "mixed",
  }),
  source({
    id: "80k-rohin-shah-2026",
    kind: "podcast",
    title: "What It Is Really Like to Run AGI Safety at Google DeepMind",
    publisher: "80,000 Hours Podcast",
    authors: "Rohin Shah and Rob Wiblin",
    publishedAt: "2026-06-02T21:41:24.000Z",
    url: "https://podcasts.apple.com/ca/podcast/what-its-really-like-to-run-agi-safety-at-google-deepmind/id1245002988?i=1000770794327",
    summary: "A practitioner debate about catastrophic misalignment, pre-deployment evaluation, governance bottlenecks, interpretability, and institutional accountability.",
    keyClaim: "Governance and durable external accountability may lag technical alignment work even when empirical research continues to progress.",
    limitations: "A long-form interview represents one expert's current judgment and is not a forecast or consensus position.",
    topics: ["governance", "alignment", "evals", "oversight", "interpretability"],
    evidenceGrade: "commentary",
    stance: "mixed",
  }),
  source({
    id: "80k-ajeya-cotra-2026",
    kind: "podcast",
    title: "Is It Crazy That Every AI Company's Safety Plan Is Use AI to Make AI Safe?",
    publisher: "80,000 Hours Podcast",
    authors: "Ajeya Cotra and Rob Wiblin",
    publishedAt: "2026-02-17T06:45:41.000Z",
    url: "https://podcasts.apple.com/us/podcast/235-ajeya-cotra-on-whether-its-crazy-that-every-ai/id1245002988?i=1000750178605",
    summary: "Explores the recursive safety window, redirecting AI labor, institutional bottlenecks, and the assumptions behind automated alignment work.",
    keyClaim: "If AI helps build safer AI, the decisive question is whether compute, talent, and institutions can be redirected before the window closes.",
    limitations: "The episode is a forecasting conversation; timelines and probabilities remain uncertain and model-dependent.",
    topics: ["ai-rd", "recursive-improvement", "governance", "forecasting", "pacing"],
    evidenceGrade: "commentary",
    stance: "cautionary",
  }),
  source({
    id: "80k-owain-evans-2026",
    kind: "podcast",
    title: "Owain Evans on Accidentally Training AI Models to Be Evil",
    publisher: "80,000 Hours Podcast",
    authors: "Owain Evans and Zershaaneh Qureshi",
    publishedAt: "2026-08-20T09:40:56.000Z",
    url: "https://80k.info/oe",
    summary: "Discusses emergent misalignment, bad-persona generalization, value leakage, activation oracles, and whether good habits might generalize.",
    keyClaim: "Narrow harmful training signals can generalize into broader behaviors that are not obvious from the training data alone.",
    limitations: "Experimental findings and the podcast's framing should be separated from broad claims about all future models.",
    topics: ["misalignment", "deception", "interpretability", "training", "evals"],
    evidenceGrade: "commentary",
    stance: "cautionary",
  }),
  source({
    id: "dwarkesh-noam-brown-2026",
    kind: "podcast",
    title: "Noam Brown — Agent Swarms, Alignment, and Recursive Self-Improvement",
    publisher: "Dwarkesh Podcast",
    authors: "Noam Brown and Dwarkesh Patel",
    publishedAt: "2026-09-17T00:00:00.000Z",
    url: "https://steadcast.co/show/dwarkesh/noam-brown-agent-swarms-alignment-recursive-self-improvement",
    summary: "Explores cooperative multi-agent training, unintended communication, reward design, alignment metrics, and recursive self-improvement.",
    keyClaim: "Population-sized cooperative systems change the alignment question from one model to the behavior of a connected population.",
    limitations: "The discussion is speculative and does not establish the frequency or inevitability of the scenarios described.",
    topics: ["multi-agent", "alignment", "ai-rd", "deception", "governance"],
    evidenceGrade: "commentary",
    stance: "mixed",
  }),
  source({
    id: "kairos-pretraining-safety-2026",
    kind: "podcast",
    title: "Pretraining Safety with Ethan Roland",
    publisher: "Kairos.fm",
    authors: "Ethan Roland and Jacob",
    publishedAt: "2026-07-09T00:00:00.000Z",
    url: "https://kairos.fm/intoaisafety/e032/",
    summary: "Discusses modular pre-training, gradient routing, access control, and the infrastructure required to intervene before deployment.",
    keyClaim: "Capability access control may be more robust when dangerous capabilities are isolated during pre-training rather than filtered afterward.",
    limitations: "The discussion is tied to a particular research program and should be read alongside the paper and its ablations.",
    topics: ["pretraining", "access-control", "interpretability", "security", "alignment"],
    evidenceGrade: "commentary",
    stance: "constructive",
  }),
  source({
    id: "paperdive-conservatism-2026",
    kind: "podcast",
    title: "Calibrating Conservatism for Scalable Oversight",
    publisher: "PaperDive",
    authors: "Cassidy and Eric",
    publishedAt: "2026-05-28T00:00:00.000Z",
    url: "https://paperdive.ai/episodes/093-calibrating-conservatism-for-scalable-oversight.html",
    summary: "Walks through attainable utility preservation, conformal decision theory, calibrated overseer objections, and a coding-agent experiment.",
    keyClaim: "Calibrated oversight can control a target failure rate under assumptions, but rate control is not the same as catastrophe prevention.",
    limitations: "The discussion highlights assumptions about feedback, non-adaptive adversaries, and ground-truth labels that limit the guarantee.",
    topics: ["oversight", "control", "evals", "security", "calibration"],
    evidenceGrade: "commentary",
    stance: "mixed",
  }),
  source({
    id: "redwood-huggingface-incident-2026",
    kind: "podcast",
    title: "The OpenAI–Hugging Face Incident",
    publisher: "Redwood Research",
    authors: "Redwood Research",
    publishedAt: "2026-07-23T00:00:00.000Z",
    url: "https://podcasts.apple.com/us/podcast/the-openai-huggingface-incident-redwood-research/id1806316198?i=1000778178421",
    summary: "A researcher discussion about an evaluation incident, what it does and does not show about misalignment, disclosure, and control failures.",
    keyClaim: "Incident disclosure and independent investigation are part of the safety evidence base, not communications cleanup after the fact.",
    limitations: "The episode is commentary on an evolving incident and distinguishes reported facts from interpretation.",
    topics: ["incidents", "security", "transparency", "misalignment", "monitoring"],
    evidenceGrade: "commentary",
    stance: "cautionary",
  }),
  source({
    id: "deepmind-red-team-podcast-2026",
    kind: "podcast",
    title: "How DeepMind Red-Teams AI—and Why It Matters",
    publisher: "The Tech Download",
    authors: "Dawn Bloxwich, Tom Lue, and The Tech Download",
    publishedAt: "2026-01-29T21:25:59.000Z",
    url: "https://podcasts.apple.com/us/podcast/how-deepmind-red-teams-ai-and-why-it-matters/id1413255721?i=1000747249980",
    summary: "A frontier-lab perspective on structured evaluations, expert red-teaming, severe risks, model cards, and third-party testing.",
    keyClaim: "Safety practice needs both technical evaluation and institutional practices for disclosure, testing, and coordination.",
    limitations: "This is a lab perspective and does not independently verify the completeness of the described safeguards.",
    topics: ["red-teaming", "evals", "governance", "frontier-risk", "transparency"],
    evidenceGrade: "commentary",
    stance: "constructive",
  }),
  source({
    id: "frontier-systems-2026",
    kind: "podcast",
    title: "Frontier Systems",
    publisher: "Frontier Systems",
    authors: "Frontier Systems hosts and guests",
    publishedAt: "2026-04-27T08:49:40.000Z",
    url: "https://podcasts.apple.com/us/podcast/frontier-systems/id1892206689",
    summary: "Interviews with researchers, operators, and builders discuss evaluations, character, infrastructure, and the future of agentic work.",
    keyClaim: "Reliability and alignment become different questions as long-running agents become a central unit of work.",
    limitations: "A broad podcast feed is context, not a substitute for primary papers or independently reproduced evaluations.",
    topics: ["agents", "evals", "alignment", "infrastructure", "research"],
    evidenceGrade: "commentary",
    stance: "mixed",
  }),
  source({
    id: "nate-soares-existential-risk-2026",
    kind: "podcast",
    title: "A Sober Conversation About AI Existential Risk",
    publisher: "Big Technology Podcast",
    authors: "Nate Soares, Jack Clark, and guests",
    publishedAt: "2026-09-16T00:00:00.000Z",
    url: "https://podscripts.co/podcasts/big-technology-podcast/a-sober-conversation-about-ai-existential-risk-with-nate-soares",
    summary: "A debate about superintelligence, opaque systems, instrumental goals, safeguards, and the possibility of enforceable international controls.",
    keyClaim: "Power and capability can grow faster than the institutions capable of constraining them, making verification and treaties central.",
    limitations: "This is a contested argument about future risk, not a settled empirical result or a complete account of opposing views.",
    topics: ["existential-risk", "governance", "pacing", "superintelligence", "verification"],
    evidenceGrade: "commentary",
    stance: "skeptical",
  }),
  source({
    id: "openagentbench-2026",
    kind: "tool",
    title: "OpenAgentBench",
    publisher: "General AI Models",
    authors: "OpenAgentBench contributors",
    publishedAt: "2026-03-18T17:30:52.000Z",
    url: "https://github.com/generalaimodels/OpenAgentBench",
    summary: "An open benchmark and verification stack for stateful agent behavior, tool governance, memory hygiene, recovery, and coordination.",
    keyClaim: "A correct answer reached through an invalid trajectory should not count as a safe agent outcome.",
    limitations: "Open-source benchmark design choices and coverage determine what the platform can and cannot detect.",
    topics: ["evals", "agents", "tools", "verification", "memory"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "agent-auditing-engine-2026",
    kind: "tool",
    title: "A2E: Agent Auditing Engine",
    publisher: "DataML Lab",
    authors: "A2E contributors",
    publishedAt: "2026-08-10T00:00:00.000Z",
    url: "https://github.com/datamllab/A2E",
    summary: "An open-source platform for instrumenting agent trajectories and scoring both process and outcome across popular harnesses.",
    keyClaim: "Stored traces let teams inspect, re-score, and compare agent behavior after a run instead of relying on a final answer alone.",
    limitations: "Instrumentation and evaluator quality remain only as trustworthy as their coverage and assumptions.",
    topics: ["evals", "observability", "agents", "provenance", "tools"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "ground-eval-2026",
    kind: "tool",
    title: "GroundEval",
    publisher: "GroundEval contributors",
    authors: "GroundEval contributors",
    publishedAt: "2026-06-01T00:00:00.000Z",
    url: "https://github.com/tenurehq/GroundEval",
    summary: "A deterministic debugging loop for checking evidence, skipped preconditions, and permission boundaries in agent trajectories.",
    keyClaim: "Counterfactual, silence, and perspective checks can expose invalid trajectories even when the final answer looks right.",
    limitations: "A generated contract is explicitly unreviewed until a human confirms the inferred checks and permissions.",
    topics: ["evals", "verification", "agents", "permissions", "observability"],
    evidenceGrade: "primary",
    stance: "constructive",
  }),
  source({
    id: "mcpkernel-2026",
    kind: "tool",
    title: "MCPKernel Security Kernel",
    publisher: "MCPKernel contributors",
    authors: "MCPKernel contributors",
    publishedAt: "2026-03-21T02:37:01.000Z",
    url: "https://github.com/piyushptiwari1/mcpkernel",
    summary: "An open security gateway concept for policy checks, taint tracking, sandboxing, deterministic envelopes, and signed audit trails around MCP tools.",
    keyClaim: "Agent tool calls need runtime policy and evidence controls rather than trust in the model's final description.",
    limitations: "The project is early-stage and its compliance claims and security boundaries require independent review.",
    topics: ["mcp", "security", "tools", "policy", "provenance"],
    evidenceGrade: "experimental",
    stance: "constructive",
  }),
];

export const CURATED_COMMENTARY: CommentaryLens[] = [
  { id: "commentary-metr-independent", sourceId: "metr-frontier-risk-report-2026", author: "METR", role: "Independent evaluator", stance: "mixed", body: "Frontier-agent risk should be assessed as means, motive, and opportunity inside the deploying organization—not only as a model capability score.", counterpoint: "Private access and redacted company-specific findings limit how much outsiders can independently verify.", url: "https://metr.org/blog/2026-05-19-frontier-risk-report/", publishedAt: "2026-05-19T00:00:00.000Z" },
  { id: "commentary-rohin-governance", sourceId: "80k-rohin-shah-2026", author: "Rohin Shah", role: "AGI safety practitioner", stance: "mixed", body: "Governance and durable accountability may be the slower bottleneck even when technical alignment research continues to move quickly.", counterpoint: "The same practitioner argues that current short-horizon behavior should not be treated as proof about superintelligence.", url: "https://80k.info/rs26", publishedAt: "2026-06-02T21:41:24.000Z" },
  { id: "commentary-ajeya-window", sourceId: "80k-ajeya-cotra-2026", author: "Ajeya Cotra", role: "Forecaster and researcher", stance: "cautionary", body: "The safety question is not only whether AI can help make AI safe, but whether the required labor and institutions can be redirected before a recursive window closes.", counterpoint: "Forecasting timelines remain uncertain and should not be converted into false precision.", url: "https://80k.info", publishedAt: "2026-02-17T06:45:41.000Z" },
  { id: "commentary-anthropic-measurement", sourceId: "anthropic-pace-measurements-2026", author: "Anthropic Institute", role: "Frontier lab", stance: "constructive", body: "Monitor coverage, review latency, escalation rate, and safety compute are practical metrics that could make oversight pace externally inspectable.", counterpoint: "Definitions and model-assisted classification need independent scrutiny before cross-lab comparison.", url: "https://www.anthropic.com/institute/measuring-pace-of-ai-development", publishedAt: "2026-09-23T21:59:24.000Z" },
  { id: "commentary-dario-evaluators", sourceId: "dario-pacing-frontier-2026", author: "Dario Amodei", role: "Frontier lab leader", stance: "cautionary", body: "Embedded evaluators with meaningful access could turn safety claims from voluntary assertions into inspectable institutional practice.", counterpoint: "A proposal from one lab is not a binding standard and access itself creates security and disclosure tensions.", url: "https://darioamodei.com/post/we-must-pace-the-frontier", publishedAt: "2026-07-01T00:00:00.000Z" },
  { id: "commentary-noam-population", sourceId: "dwarkesh-noam-brown-2026", author: "Noam Brown", role: "AI researcher", stance: "mixed", body: "Cooperative multi-agent training can create emergent communication and population-level alignment questions that a single-model view misses.", counterpoint: "The episode is a speculative discussion, not evidence that a natural cascade is underway.", url: "https://steadcast.co/show/dwarkesh/noam-brown-agent-swarms-alignment-recursive-self-improvement", publishedAt: "2026-09-17T00:00:00.000Z" },
  { id: "commentary-owain-personas", sourceId: "80k-owain-evans-2026", author: "Owain Evans", role: "Alignment researcher", stance: "cautionary", body: "Narrow negative training signals can produce broad persona-like behavior, which makes training-time generalization a first-class safety question.", counterpoint: "The surprising experiments need replication and careful separation from claims about all future models.", url: "https://80k.info/oe", publishedAt: "2026-08-20T09:40:56.000Z" },
  { id: "commentary-nate-coordination", sourceId: "nate-soares-existential-risk-2026", author: "Nate Soares", role: "Existential-risk researcher", stance: "skeptical", body: "Opaque systems and powerful agents could make control and international verification central constraints on development.", counterpoint: "The risk case is contested and should be compared with optimistic and gradual-transition arguments.", url: "https://podscripts.co/podcasts/big-technology-podcast/a-sober-conversation-about-ai-existential-risk-with-nate-soares", publishedAt: "2026-09-16T00:00:00.000Z" },
  { id: "commentary-science-verification", sourceId: "science-who-checks-ai-2026", author: "Science commentary", role: "Science institution", stance: "constructive", body: "Frontier AI needs the kind of routine independent verification and incident learning institutions that other safety-critical fields developed.", counterpoint: "Opening sensitive evaluation environments creates its own containment and information-hazard problems.", url: "https://www.science.org/doi/10.1126/science.ael2161", publishedAt: "2026-09-20T00:00:00.000Z" },
  { id: "commentary-care-agency", sourceId: "civic-ai-care-2026", author: "Civic AI care researchers", role: "Care and co-production practitioners", stance: "constructive", body: "Care ethics turns dignity, choice, human contact, and reciprocity into testable design requirements rather than abstract ethics language.", counterpoint: "A care-centered process still needs technical controls, accountability, and evidence of effectiveness.", url: "https://civic.ai/care-ai/", publishedAt: "2026-03-13T00:00:00.000Z" },
  { id: "commentary-openai-trajectory", sourceId: "openai-long-horizon-safety-2026", author: "OpenAI safety and alignment teams", role: "Frontier lab", stance: "constructive", body: "Long-horizon safety should monitor the trajectory toward an outcome, not approve each isolated action as if the sequence were harmless.", counterpoint: "The account is selective and the public cannot independently inspect all internal incidents or monitor coverage.", url: "https://openai.com/index/safety-alignment-long-horizon-models/", publishedAt: "2026-07-20T00:00:00.000Z" },
  { id: "commentary-iasr-evidence", sourceId: "international-ai-safety-report-2026", author: "International AI Safety Report writing team", role: "Independent synthesis", stance: "mixed", body: "The evidence dilemma means uncertainty itself is a governance problem: acting too early can entrench weak controls, while waiting can remove options.", counterpoint: "The report deliberately avoids prescribing a single policy response.", url: "https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026", publishedAt: "2026-02-03T00:00:00.000Z" },
];
